### ISSUE TITLE
ESLint should also be available for JSX

### ISSUE THREAD

**Issue by muuvmuuv** [Unibeautify/beautifier-eslint#72]
ESLint has a plugin integration for React: https://github.com/yannickcr/eslint-plugin-react I would like to use this instead of the other beautifiers.

**Comment by muuvmuuv** [comment]
We could add them via a plugins object in the beautifiers option. Beside that, they are added through the .eslintrc so it would not affect Unibeutify directly as they need to be installed via npm on top of the project. 

Would it possible to install packages dynamically inside a plugin? Maybe a function could handle added plugins like the npm does; so it would simply add or remove them when they appear in the settings and vice versa.

Example conf:

```
JavaScript:
     ESLint:
          plugins:
               - eslint-plugin-react
      ....
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
